### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by adamchainz** [rqlite/pyrqlite#23]
From what I see pyrqlite doesn't implement transaction support, which would be a blocker for many users: https://github.com/rqlite/pyrqlite/blob/master/src/pyrqlite/connections.py#L130

What's needed to add it?

**Comment by otoolep** [comment]
That's because rqlite doesn't support transactions in the way pyrqlite would need. rqlite supports a different type of transactions, which don't really help pyrqlite.

**Comment by adamchainz** [comment]
Ah okay. Maybe this could be added to the README.

**Comment by otoolep** [comment]
Fair: https://github.com/rqlite/pyrqlite/commit/7bc124f29fd094ab16af465317748298c04d8494

**Comment by adamchainz** [comment]
Thanks!
