### ISSUE TITLE
aiorqlite

### ISSUE THREAD

**Issue by superloach** [rqlite/pyrqlite#31]
This isn't really an issue, I just thought I'd share that I've converted this library to work with Python's asyncio and aiohttp libraries!

https://github.com/superloach/aiorqlite
https://pypi.org/project/AIOrqlite/

Any tips on improvements (or possibly ideas for moving this functionality into the main library) would be appreciated 😊

**Comment by otoolep** [comment]
@superloach -- thank you for your contribution. I suggest you let the rqlite Google Groups know about this at https://groups.google.com/forum/#!forum/rqlite

**Comment by sc68cal** [comment]
I came across this while searching, but it appears that https://github.com/superloach/aiorqlite has disappeared?
