### ISSUE TITLE
Release on PyPi?

### ISSUE THREAD

**Issue by thedrow** [rqlite/pyrqlite#33]
Why isn't there an official release yet?

**Comment by zmedico** [comment]
I think it would be a good thing to have. I've never published anything on PyPi before, which explains why it's not published yet. I'm interested in doing it.

**Comment by otoolep** [comment]
I once created an rqlite project on PyPi:

https://pypi.org/project/rqlite/

@zmedico -- if this looks like a good place to put this package, you should create an account on pypi.org, and I can add you as a "Collaborator".

**Comment by zmedico** [comment]
I've added a pyrqlite project now:

https://pypi.org/project/pyrqlite

I think that we would need to rename the module from pyrqlite to rqlite if we want to distribute it from https://pypi.org/project/rqlite/.

**Comment by otoolep** [comment]
OK, so the project I set up is just going to confuse folks? Renaming the existing package could be disruptive presumably. Is that the case?

**Comment by zmedico** [comment]
Yes, the `rqlite` project name will cause confusion because the project name should correspond to the module name, as described here:

https://www.python.org/dev/peps/pep-0423/#use-a-single-name

Renaming would cause unnecessary disruption. I've invited you as an owner to the pyrqlite project.

**Comment by otoolep** [comment]
Thanks for your help, @zmedico

**Comment by otoolep** [comment]
https://www.philipotoole.com/new-python-package-for-rqlite/
