### ISSUE TITLE
EphemeralRqlited does not wait for rqlited to become leader

### ISSUE THREAD

**Issue by zmedico** [rqlite/pyrqlite#37]
The pyrqlite unit tests fail with rqlite-6.7.0 because EphemeralRqlited does not wait for the ephemeral rqlited instance to become the leader. This problem can be solved by polling the http `/status` endpoint until `.store.raft.state` is `Leader`.

**Comment by otoolep** [comment]
Are you sure? The tests are healthy on CircleCI.

https://app.circleci.com/pipelines/github/rqlite/pyrqlite

This has been fixed in the latest code by checking a new endpoint `readyz`.

https://github.com/rqlite/pyrqlite/blob/master/src/pyrqlite/_ephemeral.py#L50

**Comment by zmedico** [comment]
I see now that we 636065fd6da04bf19b143b9a02cc224a8373498b fixed it via readyz. Thanks!
