### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by alanjds** [rqlite/pyrqlite#5]
There is no ``pyrqlite`` on the cheeseshop. Will you create one? Or maybe is ok if I do?

**Comment by otoolep** [comment]
Cheers @alanjds -- you mean a wheel, for upload, or something else?

You've seen this, right? https://pypi.python.org/pypi/rqlite/1.0

I was thinking about putting it here, so one could do `pip install rqlite`

**Comment by alanjds** [comment]
This one! I expected it to be released named as pyrqlite, but is ok. Will
issue a PR to include an example of install via pip+PyPI.

This ticket can be closed. Thanks.

Em 10 de jan de 2017 3:37 AM, "otoolep" <notifications@github.com> escreveu:

**Comment by otoolep** [comment]
Sounds good @alanjds -- thanks.

**Comment by dopaminereceptionist** [comment]
Hi! I'm not able to install from PyPi directly. Could you push it up to PyPi? Thanks!
