### ISSUE TITLE
Suggestion: sqlite3 row compatibility

### ISSUE THREAD

**Issue by mybooc** [rqlite/pyrqlite#56]
Thank you for pyrqlite.

By default, sqliite3 returns data as a tuple or a list of tuples. 
My suggestion is to add a parameter that makes pyrqlite compatible with sqlite3:

1. add parameter 'compat_rows' to connections.py.
2. then in cursors.py, replace the code:
`                    for payload_row in values:`
`                        row = []`
`                        for field, converter, value in zip(fields, converters, payload_row):`
`                            row.append((field, (value if converter is None`
`                                                else converter(value))))`
`                        rows.append(Row(row))`
by:
`                    if self._connection.compat_rows is None:`
`                        for payload_row in values:`
`                            row = []`
`                            for field, converter, value in zip(fields, converters, payload_row):`
`                                row.append((field, (value if converter is None`
`                                                    else converter(value))))`
`                            rows.append(Row(row))`
`                    elif self._connection.compat_rows == 'sqlite3':`
`                        for payload_row in values:`
`                            row = []`
`                            for field, converter, value in zip(fields, converters, payload_row):`
`                                row.append(value if converter is None`
`                                                    else converter(value))`
`                            rows.append(tuple(row))`
`                    else:`
`                        raise ValueError('compat_rows must be None or sqlite3')
` 
Thank you.

**Comment by zmedico** [comment]
The Row class already inherits tuple for sqlite3 compatibility since 62eceeffd4409c0c31c0ed41ed1e8be0e34c05ae. Is there some specific compatibility issue you are experiencing that we might be able to address in the Row class?

**Comment by mybooc** [comment]
Sorry, my bad, got confused by the OrderedDict in the example. All I wanted to do is:
`for row in rows:`
`    x, y, z = row` 
where x, y, z are the values. This works fine. Thank you for the quick response!

**Comment by zmedico** [comment]
Okay, so this Row method is a little confusing:
```python
    def __str__(self):
        return str(self._dict)
```
I suppose we could indicate the `pyrqlite.row.Row` type there, or even use the `tuple.__str__` implementation.

**Comment by mybooc** [comment]
What you want, the pyrqlite code looks great, maybe add some more text to the README.rst. I have a Python app using SQLite, and only changing the connect was needed to make it work with rqlite.  Can close this. Thanks again.
