### ISSUE TITLE
SQL expressions with the join keyword that have the same key do not correspond to the number of columns and values in the returned value

### ISSUE THREAD

**Issue by FreeKun19991215** [rqlite/pyrqlite#58]
first, this is my table creation SQL:
    CREATE TABLE IF NOT EXISTS dp_project_gateway (
        id integer primary key not null,
        name text not null,
        describe text,
        machine_id integer not null,  /* foreign_key machine(id) */
        create_time timestamp not null,
        CONSTRAINT major_sign_1 UNIQUE(name),
        CONSTRAINT major_sign_2 UNIQUE(machine_id));
    CREATE TABLE IF NOT EXISTS dp_project_strategy (
        id integer primary key not null,
        name text not null,
        describe text,
        strategy_type integer not null,
        target_type integer not null, 
        way integer,
        project_gateway_id integer not null,  /* foreign_key dp_project_gateway(id) */
        platform_type integer,
        platform_id integer, 
        raw_cycle_type integer not null, 
        raw_cycles text,
        raw_time_type integer not null,
        raw_time timestamp,
        raw_start_time timestamp,
        raw_end_time timestamp,
        raw_every_few_type integer,
        raw_every_few integer,
        reserve_count integer not null,
        CONSTRAINT major_sign UNIQUE(name, strategy_type, target_type));

then, this is my test script: 
    #!user/bin/python
    
    import pyrqlite.dbapi2 as dbapi2
    
    connection = dbapi2.connect(host='192.168.25.216', port=4001)
    with connection.cursor() as cursor:
        cursor.execute(
            'select * from dp_project_gateway inner join dp_project_strategy on dp_project_gateway.id=dp_project_strategy.project_gateway_id;')
        row = cursor.fetchone()
        print('---------------------- keys ----------------------------')
        print(list(row.keys()))
        print(f'number of keys: {len(list(row.keys()))}')
        print('---------------------- values --------------------------')
        print(row.values())
        print(f'number of values: {len(row.values())}')
        print('--------------------------------------------------------')

final, this is the output of the script in terminal:
![1704855818948](https://github.com/rqlite/pyrqlite/assets/59136294/64a56fc8-90c3-4451-b24f-2d39e965d2ab)

**Comment by otoolep** [comment]
Have you confirmed this is a Python library issue, and not an issue with rqlite itself?

Can you check the behaviour when you access the rqlite API directly?

https://rqlite.io/docs/api/api/

**Comment by FreeKun19991215** [comment]
![image](https://github.com/rqlite/pyrqlite/assets/59136294/3d20b0ff-dd89-4189-b263-0bd0731c20dc)
no problem in rqlite terminal

**Comment by FreeKun19991215** [comment]
i think the reason that is the list of key remove the same key

**Comment by FreeKun19991215** [comment]
![image](https://github.com/rqlite/pyrqlite/assets/59136294/81685f40-0e3d-457c-8eac-fa4970b30615)

It is also normal to use the rqlite API

**Comment by zmedico** [comment]
If you use the tuple interface of the [Row](https://github.com/rqlite/pyrqlite/blob/master/src/pyrqlite/row.py) class, then it should operate correctly, having the correct length and values at correct indexes.

The `keys` method does not fit nicely if there are multiple columns with identical names, since this method comes from the [Mapping](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping) interface, which implies that each key should be unique. However, I see that sqlite3.Row supports it, so I guess we should emulate that:

https://github.com/python/cpython/blob/main/Modules/_sqlite/row.c

For the `__getitem__` method, we can also emulate the pysqlite_row_subscript function which returns the value from the first matching column.

**Comment by zmedico** [comment]
I think https://github.com/rqlite/pyrqlite/pull/59 is about right.

It uses the `tuple.__str__` implementation as previously suggested in https://github.com/rqlite/pyrqlite/issues/56#issuecomment-1763493284.

**Comment by zmedico** [comment]
I noticed that the behavior is close to multidict, so I also updated the items and values methods to match that:

https://multidict.aio-libs.org/en/stable/multidict.html#multidict.MultiDict.items
https://multidict.aio-libs.org/en/stable/multidict.html#multidict.MultiDict.values

**Comment by zmedico** [comment]
We could potentially allow customization of the row class via a Cursor.row_factory attribute like sqlite3 has:

https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.row_factory
