### ISSUE TITLE
Tests always passes. Even when broken.

### ISSUE THREAD

**Issue by alanjds** [rqlite/pyrqlite#6]
Tried to add a test to the tests folder and ``setup.py test``. It passed. But the test was just a ``raise RuntimeError``.

Test environ runs the tests, but eats the errors.

**Comment by otoolep** [comment]
Hmm, that's not good. I can take a look, but it might be a little while.

**Comment by alanjds** [comment]
I got it. Is my bad.

The tests should be named ``test_*`` to fail and be a failure. If it is not named this way, it runs, fails, but is ignored by py.test

I am importing pysqlite2 tests for DB-API and adapting it for pyrqlite.
